# Generated by Django 4.2.5 on 2023-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_listing_id', models.IntegerField(max_length=12)),
                ('property_listing_street', models.TextField()),
                ('property_listing_city', models.TextField()),
                ('property_listing_state', models.CharField(max_length=100)),
                ('property_listing_zipcode', models.TextField()),
                ('property_listing_description', models.TextField(null=True)),
                ('property_listing_status', models.CharField(max_length=50)),
                ('admin_id', models.IntegerField(null=True)),
            ],
        ),
    ]
