# Generated by Django 4.2.5 on 2023-11-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_listing',
            old_name='property_listing_description',
            new_name='listing_description',
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_id',
            field=models.IntegerField(),
        ),
    ]
