# Generated by Django 4.2.7 on 2023-12-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_range',
            field=models.ForeignKey(default=150000, on_delete=django.db.models.deletion.CASCADE, to='listings.pricerange'),
            preserve_default=False,
        ),
    ]
