# Generated by Django 4.2.5 on 2023-11-21 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_property_listing_description_property_listing_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_is_featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_pic1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_pic2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_pic3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_pic4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_listing_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_neighbourhood_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_price_range_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_listing',
            name='property_type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='admin_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='listing_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_status',
            field=models.TextField(),
        ),
    ]
