# Generated by Django 4.2.5 on 2023-11-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_listing_property_listing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
