# Generated by Django 4.2.7 on 2023-12-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
    ]
