# Generated by Django 4.2.5 on 2023-11-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_listing_property_listing_pic1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_listing',
            name='id',
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
