# Generated by Django 4.2.5 on 2023-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_property_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
