# Generated by Django 4.2.5 on 2023-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_listing_property_listing_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_neighbourhood',
            fields=[
                ('property_neighbourhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_neighbourhood_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='property_price_range',
            fields=[
                ('property_price_range_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_price_range', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='property_type',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_type_name', models.TextField()),
            ],
        ),
    ]
