# Generated by Django 4.2.4 on 2023-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_listing_property_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic1',
            field=models.ImageField(default='default.jpg', upload_to='listings_pics'),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic2',
            field=models.ImageField(default='default.jpg', upload_to='listings_pics'),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic3',
            field=models.ImageField(default='default.jpg', upload_to='listings_pics'),
        ),
        migrations.AlterField(
            model_name='property_listing',
            name='property_listing_pic4',
            field=models.ImageField(default='default.jpg', upload_to='listings_pics'),
        ),
    ]
