# Generated by Django 4.2.7 on 2023-12-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancehomerealestatesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='realtor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('realtor_img', models.ImageField(upload_to='images/')),
                ('realtor_desc', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
