# Generated by Django 4.2.7 on 2023-12-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancehomerealestatesapp', '0002_realtor_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=25)),
                ('attraction_image', models.ImageField(upload_to='images/')),
                ('attraction_url', models.URLField()),
                ('attraction_desc', models.TextField()),
            ],
        ),
    ]
