# Generated by Django 4.2.7 on 2023-12-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advancehomerealestatesapp', '0003_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
